//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramAlbionFarmAlert.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timer()
        {
            this.UserSubscription = new HashSet<UserSubscription>();
        }
    
        public int Id { get; set; }
        public int IslandId { get; set; }
        public int CultureTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Culture Culture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSubscription> UserSubscription { get; set; }
        public virtual Island Island { get; set; }
    }
}
